### ISSUE TITLE
$q [user] all seems to strip floor lines

### ISSUE THREAD

**Issue by xHarlock** [markbeep/Lecturfier#89]
![image](https://user-images.githubusercontent.com/72373341/113260985-2f09f780-92cf-11eb-90d0-7f294fd5258d.png)
https://media.discordapp.net/attachments/768600365602963496/826793332121534494/SPOILER_b42d1c504715c038e8024bfc2bd336c81.png is the correct link

**Comment by xHarlock** [comment]
![image](https://user-images.githubusercontent.com/72373341/113261379-b192b700-92cf-11eb-95f2-51bd3c980ae5.png)
Calling the quote by index provides the correct link tho

**Comment by markbeep** [comment]
Thank you for mentioning this. Changed with commit 56a4c8ed8886fe99c89cdababcff498401916d9b so that underscores `_` don't get ignored anymore when using `$q all`. Right now this can result in making a whole page italic if somebody tries to grief on purpose. But when I update quotes to be paginated this shouldn't be a big problem anymore.
